### ISSUE TITLE
nitpick: disable enter-submit on search for network

### ISSUE THREAD

**Issue by Kirkkt** [vsoch/authorSynth-www#9]
Issue:
on network.html, stupid people like me may unknowingly/accidentally hit the enter key when the keyboard focus is on the author name search textfield in the body (not the universal search bar in the header), and cause the page to refresh. Would it be better for the visitors if the enter-submit were disabled?

A possible solution:
hack network.js with the following might just do it:

```
$("#search").keydown(function(event) {
  var key;
  if (window.event) {
    key = window.event.keyCode;
  } else {
    key = event.which;
  }
  return (key != 13);
}
```

**Comment by vsoch** [comment]
I would rather not disable enter-submit - there are far many more people that would intend to use it and be annoyed that it is disabled. Many thanks for the suggestion.
